/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'diegoalves' at '27/02/16 01:52' with Gradle 2.4
 *
 * @author diegoalves, @date 27/02/16 01:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
